version: '3'

tasks:
  install:
    desc: Install dependencies using poetry
    cmds:
      - poetry install --no-root
    
  precommit:
    desc: Install git hooks via pre-commit
    cmds:
      - poetry run pre-commit install

  init:
    desc: Full project setup — install deps, configure pre-commit
    deps: [install, precommit]

  cz-commit:
    desc: Create a commit using Commitizen (Conventional Commits standard)
    cmds:
      - poetry run cz commit

  cz-check:
    desc: Check if commit messages follow Conventional Commits
    cmds:
      - poetry run cz check

  cz-bump:
    desc: Bump version, tag, and update changelog using Commitizen
    cmds:
      - poetry run cz bump

  release:
    desc: Bump version and push tags (run after merge to main)
    cmds:
      - poetry run cz bump
      - git push --follow-tags

  code-upgrade:
    desc: Updates code syntax to newer versions
    platforms: [linux, darwin]
    cmds:
      - find . -type f -name "*.py"
        ! -path "./.git/*"
        ! -path "./__pycache__/*"
        ! -path "./build/*"
        ! -path "./dist/*"
        ! -path "./.venv/*"
        ! -path "./tmp/*"
        -exec poetry run pyupgrade {} +

  format:
    desc: Code formatting with black and ruff
    deps: [code-upgrade]
    cmds:
      - poetry run black .
      - poetry run ruff check . --fix

  lint:
    desc: Static code analysis with ruff
    cmds:
      - poetry run ruff check .

  docstyle:
    desc: Docstring style check
    cmds:
      - poetry run interrogate .

  check:
    desc: Full linting, audit run, and code checks
    deps: [format, lint, docstyle]

  unused-libs:
    desc: Check for unused libraries
    cmds:
      - poetry run deptry .

  run:
    desc: Run the application
    cmds:
      - poetry run python -m app.main

  docker-build:
    desc: Build the application in docker
    cmds:
      - docker build -t python-app .
  
  docker-run:
    desc: Run the application in docker
    cmds:
      - docker run -it --rm python-app

  docker:
    desc: Start the application in docker
    deps: [docker-build, docker-run]
